version: '3.2'
services:
  app:
    image: ${CONTAINER_NAME}-app:${APP_VERSION}.${BUILD_NUMBER}
    container_name: ${CONTAINER_NAME}-app
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file: .env
    restart: always
    ports:
      - target: ${NGINX_FRONTEND_PORT}
        published: ${NGINX_FRONTEND_PORT}
        protocol: tcp
        mode: host
    command: sh -c "envsubst '$$NGINX_FRONTEND_HOST $$NGINX_FRONTEND_PORT $$NGINX_FRONTEND_DIR $$CONTAINER_NAME' < /etc/nginx/conf.d/nginx.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    deploy:
      mode: replicated
      replicas: 1
