FROM node:20.18.0-slim as build

WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY package.json /app/package.json

RUN npm install --force
RUN npm install react-scripts@3.0.1 -g --force
COPY . /app
RUN npm run build

FROM nginx:alpine
COPY ./docker/nginx/nginx.template /etc/nginx/conf.d/
COPY . /app
COPY --from=build /app/dist /app/dist