export const KEYS = {
    region_list: "region_list",
    region_get_by_id: "region_get_by_id",
    cities_list: "cities_list",
    neighborhood_list: "neighborhood_list",
    neighborhood_get_by_id: "neighborhood_get_by_id",
    city_get_by_id: "city_get_by_id",
    currency_list: "currency_list",
    currency_get_by_id: "currency_get_by_id",
    characteristics_list: "characteristics_list",
    characteristics_get_by_id: "characteristics_get_by_id",
    characteristic_value_list: "characteristic_value_list",
    characteristic_value_get_by_id: "characteristic_value_get_by_id",
    category_list: "category_list",
    category_get_by_id: "category_get_by_id",
    category_list_by_parent: "category_list_by_parent",
    category_characteristics_list: "category_characteristics_list",
    category_characteristics_get_by_id: "category_characteristics_get_by_id",
    category_characteristics_value_list: "category_characteristics_value_list",
    user_list: "user_list",
    admin_list: "admin_list",
    get_me: "get_me",
    role_list: "role_list",
    admin_role_list: "admin_role_list",
};
